# Generated by Django 3.2.7 on 2021-09-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('M', 'Masculine'), ('F', 'Femenine')], max_length=1)),
                ('birthday', models.DateField()),
            ],
        ),
    ]
