# Generated by Django 3.2.7 on 2021-09-05 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_persons_data_deletecolumn'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user.person')),
            ],
        ),
    ]
